apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  labels:
    app: agrocd-demo-pipeline
  name: agrocd-demo-pipeline
spec:
  params:
    - description: The git revision
      name: gitrevision
    - description: The git repository url
      name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: agrocd-demo-pipeline-
      spec:
        params:
          - name: git-url
            value: $(params.gitrepositoryurl)
          - name: git-revision
            value: $(params.gitrevision)
        pipelineRef:
          name: agrocd-demo-pipeline
