kind: Secret
apiVersion: v1
metadata:
  name: registry-access
  labels:
    app: agrocd-trader-pipeline
    group: pipeline
data:
  REGISTRY_PASSWORD: Y2hhbmdlSXQ=
  REGISTRY_USER: Y2hhbmdlSXQ=
  REGISTRY_URL: cXVheS5pbw==
  REGISTRY_RELEASE_NAMESPACE: Y2hhbmdlSXQ=
type: Opaque
