apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  labels:
    app: sonar-trader-pipeline
  name: sonar-trader-pipeline
spec:
  params:
    - description: The git revision
      name: gitrevision
    - description: The git repository url
      name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: sonar-trader-pipeline-
      spec:
        params:
          - name: git-url
            value: $(tt.params.gitrepositoryurl)
          - name: git-revision
            value: $(tt.params.gitrevision)
        pipelineRef:
          name: sonar-trader-pipeline
