apiVersion: operators.ibm.com/v1
kind: StockTrader
metadata:
  name: ceh
spec:
  global:
    auth: basic
    healthCheck: true
    ingress: false
    istio: false
    istioNamespace: mesh
    route: true
    jsonLogging: false
    monitoring: true
    specifyCerts: true
    certs: |
      -----BEGIN CERTIFICATE-----
      MIIDDzCCAfegAwIBAgIJANEH58y2/kzHMA0GCSqGSIb3DQEBCwUAMB4xHDAaBgNV
      BAMME0lCTSBDbG91ZCBEYXRhYmFzZXMwHhcNMTgwNjI1MTQyOTAwWhcNMjgwNjIy
      MTQyOTAwWjAeMRwwGgYDVQQDDBNJQk0gQ2xvdWQgRGF0YWJhc2VzMIIBIjANBgkq
      hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8lpaQGzcFdGqeMlmqjffMPpIQhqpd8qJ
      Pr3bIkrXJbTcJJ9uIckSUcCjw4Z/rSg8nnT13SCcOl+1to+7kdMiU8qOWKiceYZ5
      y+yZYfCkGaiZVfazQBm45zBtFWv+AB/8hfCTdNF7VY4spaA3oBE2aS7OANNSRZSK
      pwy24IUgUcILJW+mcvW80Vx+GXRfD9Ytt6PRJgBhYuUBpgzvngmCMGBn+l2KNiSf
      weovYDCD6Vngl2+6W9QFAFtWXWgF3iDQD5nl/n4mripMSX6UG/n6657u7TDdgkvA
      1eKI2FLzYKpoKBe5rcnrM7nHgNc/nCdEs5JecHb1dHv1QfPm6pzIxwIDAQABo1Aw
      TjAdBgNVHQ4EFgQUK3+XZo1wyKs+DEoYXbHruwSpXjgwHwYDVR0jBBgwFoAUK3+X
      Zo1wyKs+DEoYXbHruwSpXjgwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
      AQEAJf5dvlzUpqaix26qJEuqFG0IP57QQI5TCRJ6Xt/supRHo63eDvKw8zR7tlWQ
      lV5P0N2xwuSl9ZqAJt7/k/3ZeB+nYwPoyO3KvKvATunRvlPBn4FWVXeaPsG+7fhS
      qsejmkyonYw77HRzGOzJH4Zg8UN6mfpbaWSsyaExvqknCp9SoTQP3D67AzWqb1zY
      doqqgGIZ2nxCkp5/FXxF/TMb55vteTQwfgBy60jVVkbF7eVOWCv0KaNHPF5hrqbN
      i+3XjJ7/peF3xMvTMoy35DcT3E2ZeSVjouZs15O90kI3k2daS2OHJABW0vSj4nLz
      +PQzp/B9cQmOO8dCe049Q3oaUA==
      -----END CERTIFICATE-----
  database:
    kind: db2
    db: BLUDB
    host: db2-connect-db2.devops-prereqs-44-a01ee4194ed985a1e32b1d96fd4ae346-0000.us-east.containers.appdomain.cloud
    id: DBUSER_CHANGE
    password: DBPASS_CHANGE
    port: 31495
  jwt:
    audience: stock-trader
    issuer: http://stock-trader.ibm.com
  kafka:
    address: broker-1-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-4-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-3-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-0-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-2-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-5-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093
    apiKey: APIKEY_CHANGE
    user: KAFKA_USER_CHANGE
  looper:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/looper
      tag: latest
    url: http://{{ .Release.Name }}-looper-service:9080/looper
  broker:
    replicas: 2
    autoscale: true
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/broker
      tag: latest
    url: http://{{ .Release.Name }}-broker-service:9080/broker
  account:
    enabled: true
    replicas: 2
    autoscale: true
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/account
      tag: latest
    url: http://{{ .Release.Name }}-account-service:9080/account
  messaging:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/messaging
      tag: latest
    notification:
      url: http://{{ .Release.Name }}-notification-service:9080/notification
  cloudant:
    id: CLOUDANTUSER_CHANGE
    password: CLOUDANTPASS_CHANGE
    url: https://couchdb-connect-couchdb.devops-prereqs-44-a01ee4194ed985a1e32b1d96fd4ae346-0000.us-east.containers.appdomain.cloud/
    database: account
    collector: evidence
  collector:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/collector
      tag: latest
    url: http://{{ .Release.Name }}-collector-service:9080/collector
  ldap:
    baseDN: o=ibm.com
    host: bluepages.ibm.com
    port: 389
    realm: BluePages
  mongo:
    authDB: MONGOADMIN_CHANGE
    database: ibmclouddb
    ip: 915ce0b3-e08f-4aec-b58a-47e80442c6b4-0.blijs0dd0dcr4f55oehg.databases.appdomain.cloud
    port: 30926
    user: MONGOUSER_CHANGE
    password: MONGOPASS_CHANGE
  mq:
    channel: CLOUD.APP.SVRCONN
    host: qm1-4565.qm.us-south.mq.appdomain.cloud
    id: MQUSER_CHANGE
    password: MQPASS_CHANGE
    port: 30341
    queue: LoyaltyLevelChange
    queueManager: QM1
  notificationSlack:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/notification-slack
      tag: latest
  notificationTwitter:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/notification-twitter
      tag: latest
  odm:
    id: ODMUSER_CHANGE
    password: ODMPASS_CHANGE
    url: https://odm-connect-cp4a.devops-prereqs-44-a01ee4194ed985a1e32b1d96fd4ae346-0000.us-east.containers.appdomain.cloud/DecisionService/rest/v1/ICP_Trader_Dev_1/determineLoyalty
  oidc:
    clientId: OIDCUSER_CHANGE
    clientSecret: OIDCSECRET_CHANGE
    discoveryUrl: https://keycloak-keycloak.devops-prereqs-44-a01ee4194ed985a1e32b1d96fd4ae346-0000.us-east.containers.appdomain.cloud/auth/realms/master/.well-known/openid-configuration
  openwhisk:
    id: WHISKUSER_CHANGE
    password: WHISKPASS_CHANGE
    url: https://openwhisk.ng.bluemix.net/api/v1/namespaces/jalcorn%40us.ibm.com_dev/actions/PostLoyaltyLevelToSlack
  portfolio:
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/portfolio
      tag: latest
    url: http://{{ .Release.Name }}-portfolio-service:9080/portfolio
  redis:
    cacheInterval: 60
    urlWithCredentials: REDIS_URL_CHANGE
  s3:
    enabled: false
    bucket: stock-trader
    location: us
    endpointUrl: https://s3.us-east.cloud-object-storage.appdomain.cloud
    resourceInstanceId: >-
      INSTANCE_CRN_CHANGE
    apiKey: S3_KEY_CHANGE
  stockQuote:
    replicas: 1
    autoscale: true
    maxReplicas: 10
    cpuThreshold: 75
    apiConnect: https://api.us.apiconnect.ibmcloud.com/jalcornusibmcom-dev/sb/stocks
    iexApiKey: <your IEX API key>
    iexTrading: https://cloud.iexapis.com/stable/stock
    image:
      repository: ibmstocktrader/stock-quote
      tag: latest
    url: http://{{ .Release.Name }}-stock-quote-service:9080/stock-quote
  tradeHistory:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/trade-history
      tag: latest
    url: http://{{ .Release.Name }}-trade-history-service:9080/trade-history
  trader:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: quay.io/gas_stocktrader/trader
      tag: 9311c53
  tradr:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/tradr
      tag: latest
  twitter:
    accessToken: TWITTER_TOKEN_CHANGE
    accessTokenSecret: TWITTER_SECRET_CHANGE
    consumerKey: TWITTER_CONSUMER_CHANGE
    consumerSecret: TWITTER_CONSUMER_SECRET_CHANGE
  watson:
    id: apikey
    passwordOrApiKey: WATSON_KEY_CHANGE
    url: https://api.us-south.tone-analyzer.watson.cloud.ibm.com/instances/195be178-5f78-467f-8355-99ee5772f4c2/v3/tone?version=2017-09-21&sentences=false
